services:
  wildfly:
    image: jboss/wildfly:21.0.0.Final
    ports:
      - "8080:8080"
    depends_on:
      - db
      - liquibase
    environment:
      - JAVA_OPTS=-Djboss.http.port=8080
    volumes:
      - ./target/sistema-controle-autorizacoes.war:/opt/jboss/wildfly/standalone/deployments/sistema-controle-autorizacoes.war

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://db:5432/autorizacoes
      --changeLogFile=changelog/db.changelog-master.xml
      --username=admin
      --password=admin
      update

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autorizacoes
    ports:
      - "5432:5432"
